name = "Brian O'Grady"

bio = """
I am a walrus, cookoo kachoo.


"""

skills = [
  "C++",
  "Python",
  "docker",
  "elixir",
  "Ruby",
  "Windows Administration",
  "Whimsy",
]

[[job]]
company = "CargoSense"
position = "Automation Engineer"
start = "12/04/2018"
end   = "02/02/2021"

[[job]]
company = "Intel"
position = "Engineering Labratory Technician"
start = "01/04/2024"
end   = "02/08/2022"

[[job]]
company = "H5 Data Centers"
position = "Data Center Service Technician"
start = "03/13/2025"
end   = "03/15/2026"

